version: "3.8"

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: autofixDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./data-script:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - 5432:5432
    networks:
      - backend-network

  frontendAF1:
    image: mieres/autofix-frontend:latest
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - frontend-network

  frontendAF2:
    image: mieres/autofix-frontend:latest
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - frontend-network

  frontendAF3:
    image: mieres/autofix-frontend:latest
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - frontend-network

  backendAF1:
    image: mieres/autofix-backend:latest
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - backend-network
    depends_on:
      - database

  backendAF2:
    image: mieres/autofix-backend:latest
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - backend-network
    depends_on:
      - database

  backendAF3:
    image: mieres/autofix-backend:latest
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - backend-network
    depends_on:
      - database

  nginx-frontend:
    image: nginx:latest
    restart: always
    ports:
      - "8070:80"
    volumes:
      - ./deployment/nginx-frontend.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontendAF1
      - frontendAF2
      - frontendAF3
    networks:
      - frontend-network

  nginx-backend:
    image: nginx:latest
    restart: always
    ports:
      - "8090:8090"
    volumes:
      - ./deployment/nginx-backend.conf:/etc/nginx/nginx.conf
    depends_on:
      - backendAF1
      - backendAF2
      - backendAF3
    networks:
      - backend-network

networks:
  frontend-network:
  backend-network:

volumes:
  db_data:
