pipeline{
    agent any
    stages{
        stage("Build Frontend"){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Mieres7/AutoFix-EV1-Frontend']])
                dir("AutoFix-Frontend"){
                bat "pnpm install"
                bat "pnpm run build"
                }
            }
        }
        stage("Build and Push Docker Image"){
            steps{
                script{
                    withDockerRegistry(credentialsId: 'docker-credentials'){
                    bat "docker build -t mieres/autofix-frontend:latest ."
                    bat "docker push mieres/autofix-frontend:latest"
                    }
                }                    
            }
        }
    }
}